version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0 # Use a recent version
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SESSION_TIMEOUT_MS: 15000

  kafka:
    image: confluentinc/cp-kafka:7.5.0 # Match Zookeeper version
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Host port for external clients
      - "9093:9093" # Listener port for inter-broker communication and internal clients
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,BROKER://0.0.0.0:9093 # Define listeners
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,BROKER://kafka:9093 # Crucial for external access and inter-broker communication
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT # Map listener names to protocols
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER # Set inter-broker listener
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1 # Set number of partitions
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # Set default replication factor
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Enable auto topic creation

  kafka-ui: # Optional: Kafka UI for monitoring
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka